- name: Instala MySQL 8.0.31 via RPM local
  hosts: 192.168.190.132
  become: yes
  vars:
    mysql_root_password: "q1w2e3r4"
    ansible_user: mauriciosinni

  tasks:
    - name: Copiar RPM do repositório MySQL
      ansible.builtin.copy:
        src: /home/mauriciosinni/ansible-content/files/mysql80-community-release-el9-1.noarch.rpm
        dest: /home/mauriciosinni/ansible-content/file/smysql-release.rpm
        mode: '0644'

    - name: Instalar pacote do repositório /MySQL
      ansible.builtin.yum:
        name: /home/mauriciosinni/ansible-content/files/mysql-release.rpm
        state: present

        - name: Instalar mysql-server
      ansible.builtin.yum:
        name: mysql-server
        state: present
         disable_gpg_check: true

    - name: Iniciar e habilitar MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true

