- name: Instala MySQL 8.0.31 via RPM local
  hosts: 192.168.190.132
  become: yes
  vars:
    mysql_root_password: "q1w2e3r4"
    ansible_user: mauriciosinni

  tasks:
    - name: Copiar RPM do repositório MySQL
      ansible.builtin.copy:
        src: files/mysql80-community-release-el9-1.noarch.rpm
        dest: /tmp/mysql-release.rpm

    - name: Instalar pacote do repositório MySQL
      ansible.builtin.yum:
        name: /tmp/mysql-release.rpm
        state: present

    - name: Importar chaves GPG do MySQL
      ansible.builtin.rpm_key:
        state: present
        key: "{{ item }}"
      loop:
        - https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
        - https://repo.mysql.com/RPM-GPG-KEY-mysql

    - name: Instalar mysql-server
      ansible.builtin.yum:
        name: mysql-server
        state: present

    - name: Iniciar e habilitar MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true
