- name: Instala MySQL 8.0.31 via RPM local
  hosts: 192.168.190.132
  become: yes
  vars:
    mysql_root_password: "q1w2e3r4"
    ansible_user: mauriciosinni

  tasks:
    - name: Copiar RPM do repositório MySQL
      ansible.builtin.copy:
        src: /home/mauriciosinni/ansible-content/files/mysql80-community-release-el9-1.noarch.rpm
        dest: /home/mauriciosinni/ansible-content/file/smysql-release.rpm
        mode: '0644'

    - name: Instalar pacote do repositório /MySQL
      ansible.builtin.yum:
        name: /home/mauriciosinni/ansible-content/files/mysql-release.rpm
        state: present

    - name: Copiar chave GPG do MySQL (2022)
      ansible.builtin.copy:
        src: files/RPM-GPG-KEY-mysql-2022
        dest: /home/mauriciosinni/ansible-content/files/RPM-GPG-KEY-mysql-2022
        mode: '0644'

    - name: Copiar chave GPG do MySQL (legacy)
      ansible.builtin.copy:
        src: files/RPM-GPG-KEY-mysql
        dest: /home/mauriciosinni/ansible-content/files/RPM-GPG-KEY-mysql
        mode: '0644'

    - name: Importar chave GPG (2022)
      ansible.builtin.command: rpm --import /home/mauriciosinni/mysql-aap/RPM-GPG-KEY-mysql-2022
      args:
        warn: false

    - name: Importar chave GPG (legacy)
      ansible.builtin.command: rpm --import /home/mauriciosinni/mysql-aap/RPM-GPG-KEY-mysql
      args:
        warn: false

    - name: Instalar mysql-server
      ansible.builtin.yum:
        name: mysql-server
        state: present

    - name: Iniciar e habilitar MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true

